browser=chrome
url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
implicitWait=10
Author=Archana Pawar
TestDataSheetPath=src/main/resources/testdata/LoginData.xlsx
TestDataSheet=smoke